import = [
	"/home/$USER/.config/alacritty/Themes/monokai_charcoal.toml"
]

[font]
size = 14.0

[font.bold]
family = "mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "mononoki Nerd Font"
style = "Regular"
